DROP FUNCTION md5;
DROP FUNCTION apr_md5;
DROP FUNCTION apr_crypt;
DROP FUNCTION apr_sha1;
DROP FUNCTION validate_pw;

DROP PROCEDURE md5;
DROP PROCEDURE apr_md5;
DROP PROCEDURE apr_crypt;
DROP PROCEDURE apr_sha1;
DROP PROCEDURE validate_pw;
