#!/bin/sh

# SCRIPT: maketest
# Builds the test program for the hashing routines
# Usage: maketest

# Uncomment the next 2 lines, if you set the paths manually
#APRPATH=
#APUPATH=

# Set APRPATH to where apr-1-config is located
# Set APUPATH to where apu-1-config is located

OS=`uname`

# Some variable magic

if [ -z $APRPATH ]; then
	APRCFG=`which apr-1-config`
else
	APRCFG=$APRPATH/apr-1-config
fi

if [ -z $APRCFG ] || [ ! -e $APRCFG ]; then
	echo "apr-1-config not found. Please set APRPATH at the beginning of the script."
	exit 1
fi

if [ -z $APUPATH ]; then
	APUCFG=`which apu-1-config`
else
	APUCFG=$APUPATH/apu-1-config
fi

if [ -z $APUCFG ] || [ ! -e $APUCFG ]; then
	echo "apu-1-config not found. Please set APUPATH at the beginning of the script."
	exit 1
fi

APR_FLAGS="`$APRCFG --cppflags --includes --libs --link-ld`"
APU_FLAGS="`$APUCFG --includes --link-ld --libs`"

# additional flags for Darwin
if [ "$OS" == "Darwin" ]; then
	D_C_FLAGS="-arch x86_64"
fi

if [ "$1" == "-v" ]; then
	echo "APR_FLAGS  : " $APR_FLAGS
	echo "APU_FLAGS  : " $APU_FLAGS
	echo
	echo "APRCFG     : " $APRCFG
	echo "APUCFG     : " $APUCFG
	echo
fi

# Compile the program.
gcc -o test_hash test_hash.c hash.c $APR_FLAGS $APU_FLAGS $D_C_FLAGS
