.TH php_md5 "8" "June 2015" "php_md5" "DB2 User Defined Function and Stored Procedure"
.SH NAME
php_md5 \- DB2 UDF and SP to generate an MD5 hash
.SH SYNOPSIS
>>-PHP_MD5--(--expression--)-----------------------------------><
.PP
>>-PHP_MD5--(--expression--,--hash--)--------------------------><
.SH DESCRIPTION
MD5 hash. The php_md5 routine is compatible to the PHP md5 function.
.PP
The argument can be a character string that is either a CHAR or VARCHAR not exceeding 4096 bytes.
.PP
The result of the function is CHAR(32). The result can be null; if the argument is null, the result is the null value.
.SH EXAMPLES
\fBExample 1:\fR

.br
Inserting the user \fItest\fR and the md5 hash of the clear text \fItestpwd\fR to the table \fIusers\fR.
.PP
.nf
INSERT INTO USERS (username, password)
  VALUES ('test', php_md5('testpwd'))
.fi
.PP
\fBExample 2:\fR

.br
.nf
SELECT php_md5( 'testpwd' ) FROM SYSIBM.SYSDUMMY1

1
--------------------------------
342df5b036b2f28184536820af6d1caf

  1 record(s) selected.
.fi
.PP
\fBExample 3:\fR

.br
.nf
CALL php_md5('testpwd', ?)

  Value of output parameters
  --------------------------
  Parameter Name  : HASH
  Parameter Value : 342df5b036b2f28184536820af6d1caf

  Return Status = 0
.fi
.SH AUTHOR
Written by Helmut K. C. Tessarek.
.SH "BUGS"
Hopefully none :-) But if you find one, please report it at:
.br
https://github.com/tessus/db2-hash-routines/issues
.SH "WEB SITE"
http://tessus.github.io/db2-hash-routines
