.TH sha1_hex "8" "August 2017" "sha1_hex" "DB2 User Defined Function and Stored Procedure"
.SH NAME
sha1_hex \- DB2 UDF and SP to generate an SHA1 40-character hexadecimal hash
.SH SYNOPSIS
>>-SHA1_HEX--(--expression--)--------------------------------><
.PP
>>-SHA1_HEX--(--expression--,--hash--)-----------------------><
.SH DESCRIPTION
SHA1 algorithm. The sha1_hex routine returns a 40-character hexadecimal hash.
.PP
The argument can be a character string that is either a CHAR or VARCHAR not exceeding 4096 bytes.
.PP
The result of the function is CHAR(40). The result can be null; if the argument is null, the result is the null value.
.SH EXAMPLES
\fBExample 1:\fR

.br
Inserting the user \fItest\fR and the sha1 crypted clear text \fItestpwd\fR to the table \fIusers\fR.
.PP
.nf
INSERT INTO USERS (username, password)
  VALUES ('test', sha1_hex('testpwd'))
.fi
.PP
\fBExample 2:\fR

.br
.nf
SELECT sha1_hex('testpwd') FROM SYSIBM.SYSDUMMY1

1
----------------------------------------
98ef0758e6aac6f9a9e1197548c8190b72c9581d

  1 record(s) selected.
.fi
.PP
\fBExample 3:\fR

.br
.nf
CALL sha1_hex('testpwd', ?)

  Value of output parameters
  --------------------------
  Parameter Name  : HASH
  Parameter Value : 98ef0758e6aac6f9a9e1197548c8190b72c9581d

  Return Status = 0
.fi
.SH AUTHOR
Written by Helmut K. C. Tessarek.
.SH "BUGS"
Hopefully none :-) But if you find one, please report it at:
.br
https://github.com/tessus/db2-hash-routines/issues
.SH "WEB SITE"
http://tessus.github.io/db2-hash-routines
